#!/bin/sh

xrandr	--setprovideroutputsource	modesetting NVIDIA-0
xrandr	--auto

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

#exec awesome

# update user-dirs
#exec xdg-user-dirs-update&

# enable num lock
#numlockx&

# enable input methods
#fcitx5 -d &

# show date and real time
#nohup ~/bin/dwm_time_show.sh &
#while xsetroot -name "`date` `uptime | sed 's/.*,//'`"
#do
#	sleep 1
#done &

# set random background every 10 min
#feh --bg-fill $HOME/.local/share/backgrounds/2023-01-08-09-00-00-alluring-sunset-anime-scenery-r2gmgtcp8h9iwo9u.png &
#feh --randomize --bg-fill ~/.local/share/backgrounds/* &
#while feh --randomize --bg-fill ~/.local/share/backgrounds/* 
#do
#	sleep 600
#done &

# enable touchpad tap
#exec xinput set-prop 11 323 1&

# x compation manager
#exec picom -b&

#-------------- please uncomment after install fcitx5------------------#
exec fcitx5 -d &
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"

# Here awesome is kept default
#wm=${1:-awesome}
#case "$wm" in
#    awesome)
#        exec ~/.xinit/awesome/initial &
#        exec awesome
#        ;;
#    dwm)
#        exec ~/.xinit/dwm/autostart/initial &
#        exec dwm
#        ;;
#    *)
#        echo "No known windows manager, try it as command y/n: "
#        read act
#        if [ "$act" = "y" ]; then
#            exec $1
#        fi
#        ;;
#esac

# awesome
exec ~/.xinit/awesome/initial &
exec awesome
