#!/bin/sh

log_dir="$HOME/repository/archlinux/log"
cd $log_dir 2>/dev/null
if [ "$?" != "0" ]; then
    echo "directory $log_dir not exist"
    exit 1
fi

# get date
date=$(date +'%F')
year=$(date +'%Y')
month=$(date +'%m')
day=$(date +'%d')

# make directory by time
# year month day
mkdir $year 2>/dev/null
cd $year
mkdir $month 2>/dev/null
cd $month

vim ${date}.txt
exit 0
