#!/bin/sh

# load colors
. ~/.dwm/autostart/bar_themes/onedark

cpu() {
  cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)

  printf "^c$green^ 󰻠 "
  printf "$cpu_val"
}

battery() {
  bat_capacity="$(cat /sys/class/power_supply/BAT*/capacity)"
    if [ $bat_capacity -ge 80 ]; then
        printf "^c$blue^    $bat_capacity%%"
    elif [ $bat_capacity -lt 80 ] && [ $bat_capacity -ge 50 ]; then
        printf "^c$blue^    $bat_capacity%%"
    elif [ $bat_capacity -lt 50 ] && [ $bat_capacity -ge 20 ]; then
        printf "^c$blue^    $bat_capacity%%"
    elif [ $bat_capacity -lt 20 ] && [ $bat_capacity -ge 10 ]; then
        printf "^c$blue^    $bat_capacity%%"
    else 
        printf "^c$blue^    $bat_capacity%%"
    fi
}

brightness() {
    max_brightness=$(cat /sys/class/backlight/*/max_brightness)
    brightness=$(cat /sys/class/backlight/*/brightness)
    rate=$(($brightness*100 / $max_brightness))
    printf "^c$red^   "
    printf "^c$red^ $rate%% "
}

mem() {
  printf "^c$blue^^b$black^  "
  printf "^c$blue^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

wlan() {
	case "$(cat /sys/class/net/wl*/operstate 2>/dev/null)" in
    up )
        printf "^c$blue^  󰖩  " " ^c$blue^Connected"
        ;;
    down )
        printf "^c$blue^  󰖪  " " ^c$blue^Disconnected"
        ;;
	esac
}

bluetooth() {
    # bluetooth device mac_addr used to recognized dev
    dev1="3C:B2:33:E5:F5:EE"    # HUAWEI FreeBuds 5i
    blue_state=$(bluetoothctl show|grep Powered|awk -F '[:]' '{print $2}')
    #blue_state=$(bluetooth|awk '{print $3}')
    if [ "$blue_state" = " yes" ]; then
        blue_font=""
        blue_dev=$(bluetoothctl devices Connected|awk '{print $2}')
        case "$blue_dev" in
            "$dev1" )
               blue_font="󰗾" ;;
            * )
                ;;
        esac
        printf "^c$red^ $blue_font "
    else
        printf ""
    fi
}

clock() {
    hour=$(date +'%H')
    if [ $hour -gt 6 ] && [ $hour -lt 18 ]; then
        printf "^c$white^ ^b$darkblue^ 󱑒 "
    else
        printf "^c$black^ ^b$darkblue^ 󱑄 "
    fi
    printf "^c$black^ ^b$blue^ $(date '+%H:%M:%S')  "
}

while true
do
    xsetroot -name " ✗ $(battery) $(brightness) $(wlan) $(bluetooth) $(cpu) $(mem) $(clock)"
    sleep 1
done
