#!/bin/sh

# update user-dirs
xdg-user-dirs-update

# enable num lock
numlockx

# enable mouse tap
xinput set-prop 12 357 1

# set background
feh --bg-fill $HOME/.local/share/backgrounds/2023-01-08-09-00-00-alluring-sunset-anime-scenery-r2gmgtcp8h9iwo9u.png

# no wrong bell
xset b off

# enable picom
picom -b &

# status bar
~/.dwm/autostart/status &

#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
#export XMODIFIERS="@im=fcitx"
# enable input methods
#exec fcitx5 -d &
